import './globals.css'
import CodeButton from './components/code'
import Link from 'next/link'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Link><Code text='Documentation'/></Link>
        
        {children}</body>
    </html>
  )
}
